### PR TITLE
C++ implementation of the assignment algorithm

### PR DESCRIPTION
**Pull request by karel-brinda**

### CODE REVIEW

**Comment by karel-brinda** [comment]
@salikhov-kamil Kamil, could you add a help message and some standard CLI, please?
```
$ ./prophyle_assignment 
root not found
```

**Comment by salikhov-kamil** [comment]
Karel, yes, I'll do that.
I was fighting with getopt_long function, that deals with arguments, it has possibility to do some stuff automatically..but it doesn't work yet. Anyway, it will work in some way :)

**Comment by karel-brinda** [comment]
We don't need long arguments (in Python scripts we don't use them at all). prophyle/prophyle_assignment.py is probably the only uncorrected script :). Wait a minute, I will fix it there.

**Comment by karel-brinda** [comment]
@salikhov-kamil Kamil, could you add sequence headers to the output? It is not possible to use samtools without the headers. Thx.

**Comment by simonepignotti** [comment]
@salikhov-kamil I get this error when compiling your code, could you have a look?

[make_error.txt](https://github.com/karel-brinda/prophyle/files/1102701/make_error.txt)

**Comment by karel-brinda** [comment]
@simonepignotti @salikhov-kamil It seems that Travis has exactly the same problem: https://travis-ci.org/karel-brinda/prophyle/jobs/247143796

**Comment by salikhov-kamil** [comment]
@karel-brinda I'm working on adding sequence headers, will try to do it asap
@simonepignotti I'll check this today

**Comment by simonepignotti** [comment]
@salikhov-kamil ok thanks. For testing I propose to use the bacterial tree with sampling rate 0.05 (the resulting `index.fa` measures 424MB, does this work for you?).

**Comment by salikhov-kamil** [comment]
yes, it perfectly works
can you say me how to create such a tree and index?

**Comment by simonepignotti** [comment]
You can use `$PROPHYLE_GIT/prophyle.py index` with option -s 0.05

**Comment by salikhov-kamil** [comment]
I understood why travis and Simone have compilation problems and I don't: I use clang and g++-5, and there is no errors, but with 4.9 there is a compilation error. I fixed it

**Comment by simonepignotti** [comment]
@salikhov-kamil thanks for the update, it compiles now. Still, there is a problem with trees: when I launch your program I get a `root not found` error. I guess it is due to the new structure of the trees which Karel implemented to merge them. You should build an index and have a look at the `tree.nw` file which you will find inside the index directory using `ete3 view`, but I guess the problem is the name of the root which has been changed to `merge_root`.

**Comment by salikhov-kamil** [comment]
@simonepignotti can you give me exact command that you run?
file with newick tree should be specified in this command, otherwise you get "root not found" message (I'll replace it with better message, of course)

**Comment by simonepignotti** [comment]
I ran the main `prophyle classify` command, since @karel-brinda has already integrated your program in it. That results in the following:
```
/home/pignotti/git/prophyle/prophyle/prophyle_index/prophyle_index query -k 31 -u  idx_bacteria_005/index.fa /home/pignotti/git/prophyle/tests/simulation_bacteria.1000.fq | /home/pignotti/git/prophyle/prophyle/prophyle_assignment/prophyle_assignment -m h1 -f sam idx_bacteria_005/tree.nw 31 -
```

**Comment by karel-brinda** [comment]
This is because the parameters in `propyle_assignment.py` were changed (were synchronized with other ProPhyle programs). Kamil will need to update them in `propyle_assignment` accordingly.

**Pull request closed without merging**
