### PR TITLE
C++ implementation of the assignment algorithm

### PR DESCRIPTION
**Pull request by karel-brinda**

### CODE REVIEW

**Comment by simonepignotti** [comment]
Testing all possible options (apart from tie-lca which is not implemented) I can confirm that the C++ implementation provides the same results as the Python version!

**Comment by salikhov-kamil** [comment]
@simonepignotti awesome!

**Comment by karel-brinda** [comment]
It looks good, I am going to merge it.

> Testing all possible options (apart from tie-lca which is not implemented) I can confirm that the C++ implementation provides the same results as the Python version!

@simonepignotti Would it be possible to test it automatically on Travis? We should keep both implementations synchronized and also keep testing if they really provide the same results.

**Comment by salikhov-kamil** [comment]
Actually, I need to fix two very minor difference in the output:
1) I do not minimise the tree before outputting it in SAM format
2) there is space/tab difference in one place when read is not assigned

Am I right, @simonepignotti ?
I'll fix both these things today

**Comment by karel-brinda** [comment]
Ad 1: This should not affect the results (except the SAM headers). @simonepignotti @salikhov-kamil Do you agree?

Ad 2: This should be revealed by the tests. We really need them.

**Comment by salikhov-kamil** [comment]
1. Ad 1: This should not affect the results (except the SAM headers)
I'm not sure, maybe I can assign the read to the highest node in the non-branching path instead of the lowest one? Simone told me about something like this yesterday

2. This should be revealed by the tests. We really need them.
It's a good idea to find this out through the tests

**Comment by karel-brinda** [comment]
> maybe I can assign the read to the highest node in the non-branching path instead of the lowest one

Such a case should be already fixed by `prophyle_propagation_postprocessing.py`. If a node has only one child, we move the associated sequences down to the first branching node/leave.

**Comment by salikhov-kamil** [comment]
> Such a case is treated in prophyle_propagation_makefile.py. Nodes with one child only are "invisible" during k-mer propagation.

Ok, then the problem should only be with a SAM header, and it is much easier to fix it :)

**Pull request merged**
